$
testIterations: 100,
expectedTestOutput: "start\n1\nargs: [0 = boo, 1 = undefined, 2 = 30]\nfalseboo\n0xe3\n86\nend"
$

#init:
    log("start"), next;
    let baz = false, function foo(a, b = "3", c) {
        log("args: " + args), log(baz + a), log("0xe" + b), log((54 + 2) + c), goto b, next
    }, goto a;
    log("FAIL! `next` in function worked. It's not supposed to :/ :/ :/")
#a:
    let value = 0, goto ["Position" + (value + 1)],
    log("FAIL! `next` in function worked. It's not supposed to :/ :/ :/")
#b:
    log("FAIL! `goto` in function worked. It's not supposed to :/ :/ :/")

#Position1:
    positionOne(), when (true) { log("1"), next };
    foo("boo", c = 30), next;
    goto finalMovement

#Position2:
    causeErrorFromAnUnknownFunction
#Position3:
    causeErrorFromAnUnknownFunction
#finalMovement:
    log("end"), next;
    if(false) log(3)